# .github/workflows/sbom.yml
name: Generate CycloneDX SBOM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install CycloneDX plugin
        run: npm install @cyclonedx/bom@latest --no-save

      - name: Generate SBOM
        run: |
          npx @cyclonedx/bom \
            --output-format json \
            --output-file cyclonedx-sbom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom-json
          path: cyclonedx-sbom.json
