# .github/workflows/sbom.yml
name: Generate SBOM and Scan Vulnerabilities

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'src/**'

jobs:
  build-and-sbom:
    runs-on: ubuntu-latest

    steps:
      # 1) Pull in your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Prepare Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3) Install dependencies
      - name: Install dependencies
        run: npm install

      # 4) Generate the SBOM
      - name: Generate CycloneDX SBOM
        run: |
          npm install -g @cyclonedx/cyclonedx-npm
          cyclonedx-npm --output-file bom.json

      # 5) Install Trivy
      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          trivy_version: 'v0.62.1'

      # 6) Scan for vulnerabilities
      - name: Scan for vulnerabilities
        run: |
          trivy fs --format json --output trivy-results.json .
          trivy fs --format table --output trivy-results.txt .

      # 7) Upload artifacts
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: bom.json

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: scan-results
          path: |
            trivy-results.json
            trivy-results.txt
